# Generated by Django 4.2.5 on 2023-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FilePathField(default='', path='/media'),
        ),
    ]
